-- Schema source: docs/data-model.md. Ids are generated by the application, so
-- there are no uuid defaults anywhere.
--
-- Naming convention (store code matches on these names, see store.IsUniqueViolation
-- and friends, so treat them as API):
--   <table>_pkey                       primary key
--   <table>_<columns>_uniq             unique constraint or unique index
--   <table>_<column>_fkey              foreign key
--   <table>_<column>[_<what>]_chk      CHECK constraint
--   <table>_<columns>_idx              plain index

-- +goose Up
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id            uuid        NOT NULL,
    username      text        NOT NULL,
    password_hash text        NOT NULL,
    role          text        NOT NULL DEFAULT 'user',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_uniq UNIQUE (username),
    -- Pattern is domain.UsernamePattern: stored lowercase, 3-30 chars.
    CONSTRAINT users_username_format_chk CHECK (username ~ '^[a-z0-9_]{3,30}$'),
    -- Values are domain.Roles.
    CONSTRAINT users_role_chk CHECK (role IN ('user', 'admin'))
);

-- +goose Down
DROP TABLE users;
DROP EXTENSION IF EXISTS pg_trgm;
